name: serve-docs
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pwd
      - run: echo "hello + $PYTHONPATH"
      - run: pip install mkdocs-material mkdocstrings markdown-include
      - run: mkdocs gh-deploy --force
