name: serve-docs
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: echo "/home/runner/work/py2k/py2k" >> $GITHUB_PATH
      - run: echo "/home/runner/work/py2k/py2k/py2k" >> $GITHUB_PATH
      - run: echo "$HOME"
      - run: echo "$PATH"
      - run: pip install mkdocs-material mkdocstrings markdown-include
      - run: mkdocs gh-deploy --force
        working-directory: .
