name: serve-docs
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set pythonpath
        run: |
            echo "PYTHONPATH=/home/runner/work/py2k/py2k" >> $GITHUB_ENV
            echo "/home/runner/work/py2k/py2k/py2k" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install mkdocs-material mkdocstrings markdown-include pymdown-extensions "pytkdocs==0.10.1"
          mkdocs gh-deploy --force
